[package]
name = "gen_components"
version = "0.1.0"
edition = "2021"
authors = ["Will SHENG<syf20020816@outlook.com>"]
description = "This is a Third Party Library for Makepad Widgets"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.4.1"
makepad-widgets = { path = "/Users/shengyifei/projects/makepad/makepad/widgets" }
open = { version = "5.3.0", optional = true }
rfd = "0.15.0"
unicode-segmentation = "1.11.0"
# nom = "7.1.3"
# makepad-draw = { path = "E:/Rust/try/makepad/makepad/rik/makepad/draw", version = "0.6.0" }
# makepad-derive-widget = {path = "./derive_widget", version="0.4.0"}
# makepad-zune-jpeg ={ path = "E:/Rust/try/makepad/makepad/rik/makepad/libs/zune-jpeg", version = "0.3.17" }
# makepad-zune-png ={ path = "E:/Rust/try/makepad/makepad/rik/makepad/libs/zune-png", version = "0.2.1" }
# makepad-html ={ path = "E:/Rust/try/makepad/makepad/rik/makepad/libs/html", version = "0.4.0" }
# makepad-markdown ={ path = "E:/Rust/try/makepad/makepad/rik/makepad/libs/markdown", version = "0.4.0" }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
open = "5.3.0"
rfd = "0.15.0"
